# Generated by Django 5.2.7 on 2025-11-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='MarcaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('garantia_meses', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_productos', to='producto.categoriamodel')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marca_productos', to='producto.marcamodel')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='CambioPrecioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_cuota_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_cuota_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_cambio', models.DateField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_precio', to='producto.productomodel')),
            ],
            options={
                'db_table': 'cambio_precio',
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_subcategorias', to='producto.categoriamodel')),
            ],
            options={
                'db_table': 'subcategoria',
            },
        ),
    ]
