# Generated by Django 5.2.7 on 2025-11-07 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProductoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.CharField(max_length=500)),
                ('is_main', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='producto.productomodel')),
            ],
            options={
                'db_table': 'imagen_producto',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
